export const LOAD_SPINNER='LOAD_SPINNER';
export const STUDENT_ID_LIST='STUDENT_ID_LIST';
export const STUDENT_BY_ID='STUDENT_BY_ID';
export const GET_ALL_DATA='GET_ALL_DATA';
export const GET_ALL_STUDENTS='GET_ALL_STUDENTS';
export const USER_DETAILS='USER_DETAILS';
export const LOGIN_STATUS="LOGIN_STATUS"
